// <auto-generated />
namespace CityExplorer.DatabaseLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class nullabledateTime : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nullabledateTime));
        
        string IMigrationMetadata.Id
        {
            get { return "201610311124234_nullabledateTime"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
